package commands

import (
	"testing"
)

// TestCallbackDataParsing verifies that the callback data strings generated
// by sendRepoList are correctly parsed by dispatchSettingsCallback's switch.
//
// This is a regression test for the bug where "c:arpg:2" was split as
// ["c", "arpg", "2"] and parts[1]="arpg" matched no case in the switch
// (which only had case "ar"), causing pagination buttons to do nothing.
func TestCallbackDataParsing(t *testing.T) {
	cases := []struct {
		name        string
		data        string
		wantPrefix  string // parts[1] after SplitN(data, ":", 4)
		wantAction  string // sub-action (e.g. "pg" for pagination, or the repo name)
		description string
	}{
		{
			name:        "pagination page 2 (new format)",
			data:        "c:arp:2",
			wantPrefix:  "arp",
			wantAction:  "2",
			description: "New format: c:arp:<page> — must match case 'arp'",
		},
		{
			name:        "pagination page 3 (new format)",
			data:        "c:arp:3",
			wantPrefix:  "arp",
			wantAction:  "3",
			description: "New format: c:arp:<page> — must match case 'arp'",
		},
		{
			name:        "add repo selection",
			data:        "c:ar:swaggymusic/github-bot",
			wantPrefix:  "ar",
			wantAction:  "swaggymusic/github-bot",
			description: "Repo selection: c:ar:<owner/repo>",
		},
		{
			name:        "noop (page indicator button)",
			data:        "c:noop",
			wantPrefix:  "noop",
			wantAction:  "",
			description: "No-op button (non-clickable page indicator)",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			parts := splitCallbackData(c.data)
			if len(parts) < 2 {
				t.Fatalf("%s: expected at least 2 parts, got %d (%v)", c.description, len(parts), parts)
			}
			if parts[1] != c.wantPrefix {
				t.Errorf("%s: parts[1] = %q, want %q", c.description, parts[1], c.wantPrefix)
			}
			// For pagination, verify the page number is extractable.
			if c.wantPrefix == "arp" {
				if len(parts) < 3 {
					t.Errorf("%s: expected 3 parts for pagination, got %d", c.description, len(parts))
				}
				if parts[2] != c.wantAction {
					t.Errorf("%s: parts[2] = %q, want %q", c.description, parts[2], c.wantAction)
				}
			}
			// For repo selection, verify the repo name is extractable.
			if c.wantPrefix == "ar" {
				if len(parts) < 3 {
					t.Errorf("%s: expected 3 parts for repo selection, got %d", c.description, len(parts))
				}
				joined := joinCallbackParts(parts[2:])
				if joined != c.wantAction {
					t.Errorf("%s: joined repo = %q, want %q", c.description, joined, c.wantAction)
				}
			}
		})
	}
}

// TestOldFormatWouldFail verifies that the OLD format (c:arpg:<page>) would
// have failed with the OLD parser (which used case "ar" only). This is a
// documentation test — it proves why the fix was necessary.
func TestOldFormatWouldFail(t *testing.T) {
	oldData := "c:arpg:2"
	parts := splitCallbackData(oldData)
	// With the old parser, parts[1] = "arpg", which did NOT match case "ar".
	if parts[1] != "arpg" {
		t.Fatalf("expected parts[1]='arpg' for old format, got %q", parts[1])
	}
	// The old switch only had case "ar", so "arpg" would fall through.
	// This proves the bug existed.
	if parts[1] == "ar" {
		t.Errorf("If parts[1] were 'ar', the old code would have worked — but it's 'arpg', proving the bug")
	}
	// The new code has case "arp" which handles the new format "c:arp:<page>".
	// "arpg" is no longer generated.
}

// TestPaginationButtonDataFormat verifies the exact callback data strings
// generated by sendRepoList's pagination buttons.
func TestPaginationButtonDataFormat(t *testing.T) {
	cases := []struct {
		name string
		page int
		want string
	}{
		{"next page 2", 2, "c:arp:2"},
		{"next page 3", 3, "c:arp:3"},
		{"prev page 1", 1, "c:arp:1"},
		{"prev page 4", 4, "c:arp:4"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := formatPaginationCallback(c.page)
			if got != c.want {
				t.Errorf("formatPaginationCallback(%d) = %q, want %q", c.page, got, c.want)
			}
		})
	}
}

// splitCallbackData mirrors the SplitN logic in dispatchSettingsCallback.
func splitCallbackData(data string) []string {
	return splitN(data, ":", 4)
}

// joinCallbackParts mirrors strings.Join(parts[2:], ":").
func joinCallbackParts(parts []string) string {
	return joinStrings(parts, ":")
}

// formatPaginationCallback generates the callback data for a pagination button.
func formatPaginationCallback(page int) string {
	return "c:arp:" + intToStr(page)
}

// --- Minimal helpers (to avoid importing strings in test) ---

func splitN(s, sep string, n int) []string {
	if n <= 0 {
		return nil
	}
	var result []string
	for n > 1 {
		idx := indexOf(s, sep)
		if idx < 0 {
			break
		}
		result = append(result, s[:idx])
		s = s[idx+len(sep):]
		n--
	}
	result = append(result, s)
	return result
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

func joinStrings(parts []string, sep string) string {
	if len(parts) == 0 {
		return ""
	}
	result := parts[0]
	for _, p := range parts[1:] {
		result += sep + p
	}
	return result
}

func intToStr(n int) string {
	if n == 0 {
		return "0"
	}
	neg := false
	if n < 0 {
		neg = true
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
